import xml.etree.ElementTree as xml

l_from = ['chennai', 'bangalore', 'mumbai']
l_to = ['pune', 'mumbai', 'chennai']
l_triptype = ['round-trip', 'round-trip', 'round-trip']
l_from_date = ['10-05-2020', '10-05-2020', '10-05-2020']
l_return_date = ['20-05-2020', '20-05-2020', '20-05-2020']
l_flight_num = ['AA5063', 'AB5382', 'AC8935']
l_name = ['Nitish', 'Merin', 'Arun']
l_dob = ['01-11-1996', '04-01-1995', '08-09-1993']
l_street_name = ['first street', 'second street', 'third street']
l_city_name = ['Pallikaranai', 'Perumbakkam', 'medavakkam']
l_district_name = ['Chennai', 'Chennai', 'Chennai']
l_state_name = ['Tamil Nadu', 'Tamil Nadu', 'Tamil Nadu']
l_country_name = ['india', 'india', 'india']
l_mobile_num = ['8056592536', '9096590536', '8923592576']
l_landline_num = ['04321-223653', '04321-234556', '04321-266374']
l_personal = ['nitish@gmil.com', 'merin@gmil.com', 'arun@gmil.com']
l_official = ['nitishgreens@gmil.com', 'merinhexaware@gmil.com', 'arunhexaware@gmil.com']
l_card_name = ['VISA', 'RUPAY', 'MASTER']
l_card_holder_name = ['NITISH', 'MERIN', 'ARUN']
l_card_num = ['3452678512348907', '3452678512348907', '3452678512348907']
l_cvv_num = ['092', '452', '342']
booking = xml.Element('booking')
for i in range(len(l_from)):
    pnr = xml.SubElement(booking, 'pnr')
    from_text = xml.SubElement(pnr, 'from')
    from_text.text = str(l_from[i])
    to = xml.SubElement(pnr, 'to')
    to.text = str(l_to[i])
    triptype = xml.SubElement(pnr, 'tripType')
    triptype.text = str(l_triptype[i])
    fromdate = xml.SubElement(pnr, 'fromDate')
    fromdate.text = str(l_from_date[i])
    returndate = xml.SubElement(pnr, 'returnDate')
    returndate.text = str(l_return_date[i])
    flightno = xml.SubElement(pnr, 'flightNo')
    flightno.text = str(l_flight_num[i])
    passenger_details = xml.SubElement(pnr, 'passengerDetails')
    name = xml.SubElement(passenger_details, 'name')
    name.text = str(l_name[i])
    dob = xml.SubElement(passenger_details, 'dob')
    dob.text = str(l_dob[i])
    address = xml.SubElement(passenger_details, 'address')
    street_name = xml.SubElement(address, 'streetName')
    street_name.text = str(l_street_name[i])
    city_name = xml.SubElement(address, 'cityName')
    city_name.text = str(l_city_name[i])
    district_name = xml.SubElement(address, 'districtName')
    district_name.text = str(l_district_name[i])
    state_name = xml.SubElement(address, 'stateName')
    state_name.text = str(l_state_name[i])
    Country = xml.SubElement(address, 'Country')
    Country.text = str(l_country_name[i])
    communication_details = xml.SubElement(address, 'communicationDetails')
    phone = xml.SubElement(communication_details, 'phone')
    mobile_no = xml.SubElement(phone, 'mobileNo')
    mobile_no.text = str(l_mobile_num[i])
    landline_no = xml.SubElement(phone, 'landlineNo')
    landline_no.text = str(l_landline_num[i])
    email = xml.SubElement(communication_details, 'email')
    personal = xml.SubElement(email, 'personal')
    personal.text = str(l_personal[i])
    official = xml.SubElement(email, 'official')
    official.text = str(l_official[i])
    payment_details = xml.SubElement(pnr, 'paymentDetails')
    card_name = xml.SubElement(payment_details, 'cardName')
    card_name.text = str(l_card_name[i])
    card_holder_name = xml.SubElement(payment_details, 'cardHolderName')
    card_holder_name.text = str(l_card_holder_name[i])
    card_no = xml.SubElement(payment_details, 'cardNo')
    card_no.text = str(l_card_num[i])
    cvv_no = xml.SubElement(payment_details, 'cvvNo')
    cvv_no.text = str(l_cvv_num[i])

booking = xml.tostring(booking)
file = open("Hello.xml", "wb")
file.write(booking)
print("done.....")