import json

file = open("Api.json", "r")
json_data = file.read()
obj = json.loads(json_data)
print("From:" + (obj['booking'].get('pnr').get('from')))
print("To:" + (obj['booking'].get('pnr').get('to')))
print("Triptype:" + (obj['booking'].get('pnr').get('tripType')))
print("FromDate:" + (obj['booking'].get('pnr').get('fromDate')))
print("ReturnDate:" + (obj['booking'].get('pnr').get('returnDate')))
print("FlightNumber:" + (obj['booking'].get('pnr').get('flightNo')))
print("Name:" + (obj['booking'].get('pnr').get('passengerDetails').get('name')))
print("DOB:" + (obj['booking'].get('pnr').get('passengerDetails').get('dob')))
print("StreetName:" + (obj['booking'].get('pnr').get('passengerDetails').get('address').get('streetName')))
print("CityName:" + (obj['booking'].get('pnr').get('passengerDetails').get('address').get('cityName')))
print("StateName:" + (obj['booking'].get('pnr').get('passengerDetails').get('address').get('stateName')))
print("CountryName:" + (obj['booking'].get('pnr').get('passengerDetails').get('address').get('country')))
l = obj['booking'].get('pnr').get('passengerDetails').get('address').get('communicationDetails')
print("MobileNumber:" + l[0].get('phone').get('mobileNo'))
print("LandlineNumber:" + l[0].get('phone').get('landlineNo'))
print("PersonalEmail:" + l[1].get('email').get('personal'))
print("OfficialEmail:" + l[1].get('email').get('official'))
print("CardName:" + (obj['booking'].get('pnr').get('paymentDetails').get('cardName')))
print("CardHolderName:" + (obj['booking'].get('pnr').get('paymentDetails').get('cardHolderName')))
print("CardNumber:" + (obj['booking'].get('pnr').get('paymentDetails').get('cardNo')))
print("CvvNumber:" + (obj['booking'].get('pnr').get('paymentDetails').get('cvvNo')))
file.close()

