import xml.etree.ElementTree as xml

parse = xml.parse(r"C:\Users\k_sur\PycharmProjects\Api\Tickets")
getroot = parse.getroot()
for sub in getroot:
    print("from:" + sub[0].text)
    print("to:" + sub[1].text)
    print("trip type is:" + sub[2].text)
    print("from date:" + sub[3].text)
    print("return date:" + sub[4].text)
    print("return date:" + sub[5].text)
    print("*************Passenger Details*************")
    print("passenger name:" + sub[6][0].text)
    print("passenger dob:" + sub[6][1].text)
    print("*************Passenger Address*************")
    print("street name:" + sub[6][2][0].text)
    print("city name:" + sub[6][2][1].text)
    print("district name:" + sub[6][2][2].text)
    print("state name:" + sub[6][2][3].text)
    print("country name:" + sub[6][2][4].text)
    print("*************Communication Details*************")
    print("phone:" + sub[6][2][5][0][0].text)
    print("land line:" + sub[6][2][5][0][1].text)
    print("personal email:" + sub[6][2][5][1][0].text)
    print("official email:" + sub[6][2][5][1][1].text)
    print("*************Payment Details*************")
    print("card name:" + sub[7][0].text)
    print("card holder name:" + sub[7][1].text)
    print("card number:" + sub[7][2].text)
    print("cvv number:" + sub[7][3].text)
    print('####################################################')
